### ISSUE TITLE
Provide a simple asset/log templating mechanism + UI for authoring plugins in that template format

### ISSUE THREAD

**Issue by symbioquine** [symbioquine/farmOS_asset_link#23]
Asset Link should include a simple asset/log templating format + UI for authoring plugins in that format.

This will probably be based on the following example, but using jmespath for the string templating;

> * [LogChangedEquipmentOil.alink.act.json](https://gist.github.com/symbioquine/9a6921914a70f56792e04056b5fc0ce1) -  Example simplified custom plugin format
> * [BasicAssetLogPluginFormat.alink.js](https://gist.github.com/symbioquine/bd2b9762286089f10ff46e133dba9450) - Supports plugins of the above format
> 
> ![image](https://user-images.githubusercontent.com/30754460/218329298-fa380eeb-5aff-486e-9c73-64af66ae1a3f.png)
> 
> ![912b52aa017c670e93a79835411ad53592ec5c6f](https://user-images.githubusercontent.com/30754460/218329372-db33ffa7-91a7-4bd9-87e0-f308c39136f9.gif)

**Comment by symbioquine** [comment]
![image](https://user-images.githubusercontent.com/30754460/225106862-8055c7c4-2e1f-4729-a88e-2e6a54c7f4d7.png)

![image](https://user-images.githubusercontent.com/30754460/225107532-f68e684d-7ddb-41a1-8328-091791942795.png)

**Comment by symbioquine** [comment]
[2023_03_14_tease_plugin_creation_ui.webm](https://user-images.githubusercontent.com/30754460/225133014-9022982a-822c-4fc6-b135-bbe37dc56380.webm)

**Comment by altix12** [comment]
@symbioquine  hi, this is a great solutions but the created plugin for asset button log not saved into a file ....so if you clear the cache the plugin will not be loaded anymore

**Comment by symbioquine** [comment]
This was released in [1.0.0-alpha5](https://github.com/symbioquine/farmOS_asset_link/blob/development/CHANGELOG.md#100-alpha5---2023-03-14) - closing.

-----

> @symbioquine hi, this is a great solutions but the created plugin for asset button log not saved into a file ....so if you clear the cache the plugin will not be loaded anymore

Thanks @altix12!

Yeah, that is true of any locally installed plugin. Furthermore, plugins created locally are not available to other users of the same farmOS instance. (Without manual steps to copy the plugin code/json into a file and [serve it from farmOS](https://symbioquine.github.io/farmOS_asset_link/tutorial-plugin-as-farm-os-module.html).)

Both of those shortcomings can be addressed by providing better tooling for saving/sharing the resulting plugins. See: https://github.com/symbioquine/farmOS_asset_link/issues/33
