### ISSUE TITLE
Plugin Lists not persisting through browser restarts.

### ISSUE THREAD

**Issue by Farmer-Eds-Shed** [symbioquine/farmOS_asset_link#3]
Plugin lists added via URL do not persist through browser restarts or page refresh, with both Firefox and Chrome.

**Comment by symbioquine** [comment]
I can reproduce this by adding the plugin list https://gist.githubusercontent.com/symbioquine/8ba75c6ff5fcd3d174d21548c35b1f29/raw/36ab016bf561c95b3b2dfc25cb83f807ff0e43e0/example-plugins.repo.json and then refreshing;

[2022_08_31_issue_3_extra_plugin_lists_not_persisting.webm](https://user-images.githubusercontent.com/30754460/187726528-df698fdd-a0ad-4481-b59b-c42dbfdf2d59.webm)

**Comment by symbioquine** [comment]
Fixed by https://github.com/symbioquine/farmOS_asset_link/commit/91734b2a7395bac645ccc3ce0154d99059ef857a in the [0.6.1 release](https://www.drupal.org/project/farmos_asset_link/releases/0.6.1).
