### ISSUE TITLE
Report of Asset Link not loading

### ISSUE THREAD

**Issue by symbioquine** [symbioquine/farmOS_asset_link#34]
![image](https://user-images.githubusercontent.com/30754460/222908740-c564b31c-6611-4eb5-bbe8-78008775afae.png)

https://farmos.discourse.group/t/asset-link-dev-log/1175/39

**Comment by altix12** [comment]
hi, thanks for the help. My install of farmos  is the last , Asset link module is the last ( 1.00 alpha 3)  and this is the console issue of chrome
![Screenshot 2023-03-04 alle 18 14 45](https://user-images.githubusercontent.com/33596048/222919883-de5e9386-67b8-486a-bbab-abcb148492f7.png)

**Comment by symbioquine** [comment]
@altix12 that's helpful I think I can fix one bug just from that (it shouldn't be trying to parse the 403 error body as JSON), but there's also something else needed in order to make Asset Link operational... any chance you can check the network tab and see more details of those HTTP 403 errors for `/subrequests`? Also, what permissions does your user have - i.e. `farm_viewer`, `farm_manager`, etc? I assume you're logged in already?

**Comment by Farmer-Eds-Shed** [comment]
@altix12 you are hardly using a custom docker image with non standard tag?

@symbioquine this looks familiar is it similar to when I first tried running AssetLink on a non dev image and got caught by this check?

      if (farmOsVersion !== '2.x') {
        this.canReachFarmOS.value = false;
        return;

**Comment by altix12** [comment]
@symbioquine i logged in as farm manager and i don't know why i have those 403 errors on /subrequests. Asset link I installed it manually and I'm noticing that installing it with dush doesn't work for me. Manually instead it installs fine even if I see another module calledf armos_vue_demo_page but this not install.
![Screenshot 2023-03-04 alle 19 30 53](https://user-images.githubusercontent.com/33596048/222922976-6a8206bf-fc24-443c-9079-5d74eb878b92.png)

**Comment by altix12** [comment]
@Farmer-Eds-Shed my farmos installation is on an online server.... maybe that's the problem ( i use php 8.2.3)

**Comment by symbioquine** [comment]
> Asset link I installed it manually and I'm noticing that installing it with drush doesn't work for me.

Can you describe what you mean by "installed it manually"? (Through the Drupal UI should also work if that's what you mean.)

> I see another module called farmos_vue_demo_page
> ![](https://user-images.githubusercontent.com/33596048/222922976-6a8206bf-fc24-443c-9079-5d74eb878b92.png)

Oh, yeah that's a bug, but probably not related to the 403 errors either.

**Comment by symbioquine** [comment]
> > I see another module called farmos_vue_demo_page
> > ![](https://user-images.githubusercontent.com/33596048/222922976-6a8206bf-fc24-443c-9079-5d74eb878b92.png)
> 
> Oh, yeah that's a bug, but probably not related to the 403 errors either.

The farmos_vue_demo page bug will be fixed in the next release by https://github.com/symbioquine/farmOS_asset_link/commit/6b7f26b02e267f7d872c9d4f921e3f803a1a3538 (As I said before, it won't fix the 403 errors, but still good to squash that bug.)

**Comment by Farmer-Eds-Shed** [comment]
> @Farmer-Eds-Shed my farmos installation is on an online server.... maybe that's the problem ( i use php 8.2.3)

Ah OK, could still be related.
If you go to Admin, Reports, Status Report what is the exact version shown for farmOS installation profile?

**Comment by symbioquine** [comment]
> @symbioquine this looks familiar is it similar to when I first tried running AssetLink on a non dev image and got caught by this check?

Could be, but personally I suspect this case is a little different...

**Comment by Farmer-Eds-Shed** [comment]
Maybe not related would be any easy check for @altix12 to confirm if farmOS version is showing correctly in the Status Report.

For reference our conversation on that issue was in element chat room on 23/24 Aug

I was getting the same 403 and Json errors

**Comment by altix12** [comment]
> > Asset link L'ho installato manualmente e sto notando che l'installazione con drush non funziona per me.
> 
> Puoi descrivere cosa intendi per "installato manualmente"? (Attraverso l'interfaccia utente di Drupal dovrebbe funzionare anche se è questo che intendi.)
> 
> > Vedo un altro modulo chiamato farmos_vue_demo_page
> > ![](https://user-images.githubusercontent.com/33596048/222922976-6a8206bf-fc24-443c-9079-5d74eb878b92.png)


yes through the drupal user interface

**Comment by altix12** [comment]
> Forse non correlato sarebbe un controllo facile@altix12per confermare se la versione di farmOS viene visualizzata correttamente nel rapporto di stato.
> 
> Per riferimento, la nostra conversazione su tale questione è stata nella chat room del 23/24 agosto
> 
> Stavo ricevendo gli stessi errori 403 e Json
I'm an Italian farmer and I've been using farmos since the first version....and it's really a great tool...thanks to all of you for this great tool

![Screenshot 2023-03-04 alle 20 33 32](https://user-images.githubusercontent.com/33596048/222925408-c01adda9-d0cf-4eec-98a7-8e9d5996269d.png)

![Screenshot 2023-03-04 alle 20 34 25](https://user-images.githubusercontent.com/33596048/222925409-e9bc5764-1e73-47c5-a052-1f783fa6582a.png)

![Screenshot 2023-03-04 alle 20 34 45](https://user-images.githubusercontent.com/33596048/222925412-983bc154-9e5e-4be7-b778-df312ff77960.png)

**Comment by symbioquine** [comment]
In the modules page, do you see this?

![image](https://user-images.githubusercontent.com/30754460/222925502-6e065e83-85d4-414e-8b04-0ce253564786.png)

If so, next try going to `https://mysite.example.com/admin/people/permissions/module/subrequests` and seeing if it looks like this;

![image](https://user-images.githubusercontent.com/30754460/222925541-1eb2242b-7339-401c-96f4-0175f126da06.png)

**Comment by altix12** [comment]
> In the modules page, do you see this?
> 
> ![image](https://user-images.githubusercontent.com/30754460/222925502-6e065e83-85d4-414e-8b04-0ce253564786.png)
> 
> If so, next try going to `https://mysite.example.com/admin/people/permissions/module/subrequests` and seeing if it looks like this;
> 
> ![image](https://user-images.githubusercontent.com/30754460/222925541-1eb2242b-7339-401c-96f4-0175f126da06.png)

yes, I had already checked
![Screenshot 2023-03-04 alle 20 41 37](https://user-images.githubusercontent.com/33596048/222925724-3d4f211e-6c9c-4701-99b7-ceeed802d90f.png)

![Screenshot 2023-03-04 alle 20 42 26](https://user-images.githubusercontent.com/33596048/222925728-f04538af-1bc3-423c-b29d-5fd5c88fc0ff.png)

**Comment by altix12** [comment]
@symbioquine  seeing your picture i don't have rabbit plugin

**Comment by symbioquine** [comment]
> @symbioquine seeing your picture i don't have rabbit plugin

Good eye, but you don't need that. That's a custom module for my use-case.

**Comment by altix12** [comment]
> > @symbioquinevedendo la tua foto non ho plug coniglio
> 
> Buon occhio, ma non ne hai bisogno. Questo è un modulo personalizzato per il mio caso d'uso.

thanks and that i was also trying to figure out the reason for those 403 errors but i don't have all these skills

**Comment by symbioquine** [comment]
> thanks and that i was also trying to figure out the reason for those 403 errors but i don't have all these skills

No problem. Thanks for helping dig into this! I think we'll probably be able to figure it out...

> any chance you can check the network tab and see more details of those HTTP 403 errors for `/subrequests`?

Coming back to my original question, are you able to check the network tab when you try and open Asset Link?

![image](https://user-images.githubusercontent.com/30754460/222926190-e1284617-eadc-4ce1-a574-eb458483d2d3.png)

Then click on one of the failed `/subrequests` requests and look at the "Response" tab for that request;

![image](https://user-images.githubusercontent.com/30754460/222926243-d3078137-b5f6-4685-b26b-7a3619b4d9a6.png)

I'm hoping there will be more details about the actual 403 error in the response...

**Comment by altix12** [comment]
here is the screenshot
![Screenshot 2023-03-04 alle 21 05 46](https://user-images.githubusercontent.com/33596048/222926576-ce36eaca-5f22-4e56-b5eb-a5c76b85e55c.png)

on chrome tell me if there is a method to export console errors so maybe it will be more complete



![Screenshot 2023-03-04 alle 21 11 46](https://user-images.githubusercontent.com/33596048/222926708-a04b4b69-ac3a-4a69-af38-a7ff1d0c3776.png)

**Comment by symbioquine** [comment]
Hmmm, yeah that's what I was trying to see, but sadly it's not telling us why.

Maybe the errors on the Drupal/farmOS side will be more informative. Can you try going to `https://mysite.example.com/admin/reports/dblog` and see what errors/warnings are showing up there that might be related?

**Comment by altix12** [comment]
> Hmmm, sì, è quello che stavo cercando di vedere, ma purtroppo non ci dice perché.
> 
> Forse gli errori sul lato Drupal/farmOS saranno più informativi. Puoi provare ad andare su `https://mysite.example.com/admin/reports/dblog`e vedere quali errori/avvisi vengono visualizzati lì che potrebbero essere correlati?

sure i have these kind of log errors in farmos which all lead to ad .../alink

![Screenshot 2023-03-04 alle 21 37 20](https://user-images.githubusercontent.com/33596048/222927697-9ed09ece-84c7-4dac-9f97-69b19ce64a53.png)

**Comment by symbioquine** [comment]
> sure i have these kind of log errors in farmos which all lead to ad .../alink

Hmmm, that could be related, but I suspect that's just a warning that shouldn't be the cause of the 403 errors...

Are there any other types of warnings/errors related the `/subrequests` request(s) from loading Asset Link?

These should have the "Referrer" set to `https://mysite.example.com/alink/[something]` and have the "Location" set to `[[some server]](https://mysite.example.com)/subrequests`

![image](https://user-images.githubusercontent.com/30754460/222929080-33dd545f-d760-43c3-bd40-b8960b6f3ff8.png)

**Comment by altix12** [comment]
hi, @symbioquine  i have this error for /subrequests
![Screenshot 2023-03-05 alle 07 24 02](https://user-images.githubusercontent.com/33596048/222945327-6082ac0c-addf-4225-8d53-881101b28ac1.png)

and this for asset link 

![Screenshot 2023-03-05 alle 07 29 32](https://user-images.githubusercontent.com/33596048/222945518-b44bbafd-4e9d-43a7-9264-74f4e57f8f9e.png)

**Comment by symbioquine** [comment]
> i have this error for /subrequests
> ![Screenshot 2023-03-05 alle 07 24 02](https://user-images.githubusercontent.com/33596048/222945327-6082ac0c-addf-4225-8d53-881101b28ac1.png)

This first one looks promising @altix12 !

I'm trying to reproduce how your site is configured to see if I can recreate the problem on my end. I already have the language set to Italian. What modules do you have installed/enabled?

**Comment by altix12** [comment]
@symbioquine  i have all module installed with google and mapbox map

**Comment by symbioquine** [comment]
> @symbioquine i have all module installed with google and mapbox map

What do you mean by "all module installed"? Do you mean that you checked every box on the `https://mysite.example.com/admin/modules` page?

**Comment by altix12** [comment]
@symbioquine yes

**Comment by symbioquine** [comment]
>> What do you mean by "all module installed"? Do you mean that you checked every box on the `https://mysite.example.com/admin/modules` page?
>
> @symbioquine yes

I don't think that's a supported installation strategy in general. There are a bunch of modules that aren't really intended for real use (e.g. "Migrate Example", "Entity Browser example", etc) and modules that definitely haven't been tested with farmOS / Asset Link (e.g. "Forum", "Node", etc).

I found one additional general compatibility issue that I'll fix (for me, this was sufficient to allow Asset Link to load), but I'm not interested in trying to support all possible module combinations with Asset Link - I don't think that is a good use of my time (or yours). That said, if you can figure out what modules you actually need for your use-case I'm happy to try and make Asset Link not break when used with them.

If you're just getting started with farmOS I'd recommend enabling just the [main farmOS modules](https://github.com/farmOS/farmOS/blob/d8ff8e1cbdf201b97a322cc60c9fd44133743e26/farm.profile#L21-L45) and their dependencies, then only enabling additional modules as required to meet your use-case(s).

**Comment by altix12** [comment]
Thanks, now I'll try to reinstall farmos to see if maybe I have some module that conflicts with asset link

**Comment by altix12** [comment]
@symbioquine on a fresh install of farmos with the main modules of farmos asset link doesn't work (always error 403 /subrequests). 

EDIT: asset link installs correctly via the drupal panel while if I try to install it with drush it doesn't work
![Screenshot 2023-03-06 alle 11 57 30](https://user-images.githubusercontent.com/33596048/223092437-0d194559-aea7-4d7e-81f8-161ccf230e19.png)

EDIT2: I installed farmos manually from the github release package with the default farmos modules selected

**Comment by symbioquine** [comment]
> on a fresh install of farmos with the main modules of farmos asset link doesn't work (always error 403 /subrequests).

I'm fairly confident this is something to do with how you've got farmOS/Drupal installed rather than an issue with Asset Link - that said, I've made a change (pending release) to allow Asset Link to fall back on not using subrequests: https://github.com/symbioquine/farmOS_asset_link/commit/020e413fd1261ba703e19bbcb2cd6c4f6506afb5

> EDIT: asset link installs correctly via the drupal panel while if I try to install it with drush it doesn't work
> ![Screenshot 2023-03-06 alle 11 57 30](https://user-images.githubusercontent.com/33596048/223092437-0d194559-aea7-4d7e-81f8-161ccf230e19.png)

I just tried on a plain farmOS 2.0.1 installation and Asset Link installs/works out of the box with only these two commands;

```bash
composer require 'drupal/farmos_asset_link:^1.0@alpha'
drush en farmos_asset_link
```

I'd have to guess there's something about your configuration that is different - my first guesses would be the location of the files or permissions.

Perhaps you can share the commands (or detailed steps) you're running to get the module files into your farmOS install and the drush command you're running?

**Comment by altix12** [comment]
> > su una nuova installazione di farmos con i moduli principali di farmos asset link non funziona (sempre errore 403 /subrequests).
> 
> Sono abbastanza fiducioso che questo abbia a che fare con il modo in cui hai installato farmOS/Drupal piuttosto che con un problema con Asset Link - detto questo, ho apportato una modifica (in attesa di rilascio) per consentire a Asset Link di ripiegare su non utilizzando le sottorichieste: [020e413](https://github.com/symbioquine/farmOS_asset_link/commit/020e413fd1261ba703e19bbcb2cd6c4f6506afb5)
> 
> > EDIT: asset link si installa correttamente tramite il pannello drupal mentre se provo ad installarlo con drush non funziona
> > ![Screenshot 2023-03-06 alle 11 57 30](https://user-images.githubusercontent.com/33596048/223092437-0d194559-aea7-4d7e-81f8-161ccf230e19.png)
> 
> Ho appena provato su una semplice installazione di farmOS 2.0.1 e Asset Link si installa/funziona immediatamente con solo questi due comandi;
> 
> ```shell
> composer require 'drupal/farmos_asset_link:^1.0@alpha'
> drush en farmos_asset_link
> ```
> 
> Dovrei indovinare che c'è qualcosa nella tua configurazione che è diverso: la mia prima ipotesi sarebbe la posizione dei file o delle autorizzazioni.
> 
> Forse puoi condividere i comandi (o i passaggi dettagliati) che stai eseguendo per ottenere i file del modulo nell'installazione di farmOS e il comando drush che stai eseguendo?


the command i used is drush en farmos_asset_link. The result is the error message I linked in the picture,if instead I install the module from the drupal panel the installation is successful but the asset lnk doesn't work.... maybe if I could try the package with the changes that doesn't require the use of /subrequests maybe it could work?

**Comment by altix12** [comment]
@symbioquine  the last release  alpha 4  (6 min ago) work !! thanks ... the problem is /subrequests error  

EDIT:Asset Links is really a great tool... kudos for this wonderful tool. A question if I can but for each asset can I add an activity log?

**Comment by symbioquine** [comment]
> the command i used is drush en farmos_asset_link. The result is the error message I linked in the picture

What did you do before running the drush command? i.e. How did you get the farmos_asset_link module into your server's filesystem?

*If I run `drush en farmos_asset_link` without doing the `composer require` command first, I get the same message about the module being missing.*

> @symbioquine the last release 8 (6 min ago) work !! thanks ...

Same question here. I haven't created the release yet on drupal.org so the new release shouldn't be installable yet without some manual steps...

> the problem is /subrequests error

Again, I'd guess this is something wrong with the farmOS/Drupal installation, not Asset Link. You'll probably want to get subrequests working since it is [also likely that Field Kit](https://github.com/farmOS/farmOS.js/blob/365a52e7d6a6e116304902897b278ac7eca80728/src/client/adapter/subrequest.js) (and probably core farmOS functionality in the future) will depend on it.

I'm going to close this, since I'm fairly certain all these things can pretty much be attributed to quirks of how you're installing and setting up farmOS/Drupal.

Thanks for taking the time to try out Asset Link! Please feel free to open new issues if you find problems - including the subrequests problem if, for example, you can show that subrequests works correctly via curl but not via Asset Link.
