### ISSUE TITLE
sync error

### ISSUE THREAD

**Issue by altix12** [symbioquine/farmOS_asset_link#36]
I get an error when I try to add a log to an asset in asset link

![Screenshot 2023-03-06 alle 19 20 55](https://user-images.githubusercontent.com/33596048/223197373-27eed148-a287-47b4-a447-6d68a7c06bea.png)

**Comment by symbioquine** [comment]
What error/failure do you see in the console/network tab?

**Comment by altix12** [comment]
this screenshot 
![Screenshot 2023-03-06 alle 19 27 32](https://user-images.githubusercontent.com/33596048/223198744-5e61d740-de10-4d09-b1fa-740aa7b315d2.png)

**Comment by symbioquine** [comment]
On the network tab, click on the request to `/api/log/observation` that's failing. We need to see the "Response" tab of the request.

**Comment by symbioquine** [comment]
In Chrome you can also right click and do "Copy -> Copy Response". (In Firefox it's "Copy Value -> Copy Response")

**Comment by altix12** [comment]
![Screenshot 2023-03-06 alle 19 37 40](https://user-images.githubusercontent.com/33596048/223200803-911a2889-163a-4eb0-ae43-fe3752719f53.png)

![Screenshot 2023-03-06 alle 19 39 14](https://user-images.githubusercontent.com/33596048/223201097-2e6f320f-ecee-4ef3-9ff4-18b3618c99e8.png)

 it always looks like a 403 error

**Comment by symbioquine** [comment]
What are the response headers?

**Comment by altix12** [comment]
> What are the response headers?

![Screenshot 2023-03-06 alle 19 42 58](https://user-images.githubusercontent.com/33596048/223202271-3cb37b0d-6055-4934-a8f6-058efc24305b.png)

**Comment by symbioquine** [comment]
Is there a more informative error on the Drupal side at `https://mysite.example.com/admin/reports/dblog`?

**Comment by altix12** [comment]
> Is there a more informative error on the Drupal side at `https://mysite.example.com/admin/reports/dblog`?

only this 
![Screenshot 2023-03-06 alle 19 57 57](https://user-images.githubusercontent.com/33596048/223205092-7292962b-38f2-4799-8064-bac0352d91a4.png)
 

Could it be a problem with the API sync?

**Comment by altix12** [comment]
@symbioquineI don't know if it helps but this plugin is empty for me.... I'm sorry, maybe it has nothing to do with it, but I don't know much about these things.... ...asset link  reads the server data but doesn't write the new data

![Screenshot 2023-03-06 alle 20 14 14](https://user-images.githubusercontent.com/33596048/223208126-5a84717d-2ba3-499b-9816-bf45cb16b858.png)

**Comment by symbioquine** [comment]
> I don't know if it helps but this plugin is empty for me.... I'm sorry, maybe it has nothing to do with it, but I don't know much about these things.... ...asset link reads the server data but doesn't write the new data

Hmmm, that's also a problem, but probably a different one - or maybe related to some much deeper issue with the setup. Let's take this one step at a time.

> only this
> 
> Could it be a problem with the API sync?

I'm guessing not.

If you're not seeing permission errors/warnings in the Drupal dblog report, I think you probably have an underlying configuration problem with Drupal/Apache. My next hypothesis at this point would be that no POST requests are working on your Drupal site.

To disprove that hypothesis, can you try creating an asset or log directly in the main farmOS UI and check the network tab? Are there HTTP POST requests there that worked?

If those are also failing, it points to a general web server or Drupal configuration problem and you'll need to get that working first.

If they are succeeding, it might be a problem more specific to the farmOS API or how Asset Link is using it and the next step would be to try some simple requests to create data via the `curl` command-line program;

```bash
OAUTH2_ACCESS_TOKEN=`curl -X POST -d "grant_type=password&username=root&password=test&client_id=farm&scope=farm_manager" https://mysite.example.com/oauth/token | grep -Po 'access_token":"\K[^"]+'`
curl -X POST --header "Authorization: Bearer $OAUTH2_ACCESS_TOKEN" --header 'Content-type: application/vnd.api+json' -d '{ "data": { "type": "log--observation", "attributes": { "name": "Testing Observation 123" } } }' "https://mysite.example.com/api/log/observation"
```

***Note:** Obviously, you'll have to customize the urls and username/password in the commands above*

For more information see:

* https://www.drupal.org/docs/core-modules-and-themes/core-modules/jsonapi-module/creating-new-resources-post#s-request-body
* https://farmos.org/development/api/

**Comment by altix12** [comment]
> Per confutare questa ipotesi, puoi provare a creare una risorsa o accedere direttamente all'interfaccia utente principale di farmOS e controllare la scheda di rete? Ci sono richieste HTTP POST lì che hanno funzionato?
> 

creating an activity log or accessing the farmos main screen HTTP POST requests work correctly....could it be some problem with the write permissions of asset link ?

**Comment by symbioquine** [comment]
> HTTP POST requests work correctly....could it be some problem with the write permissions of asset link ?

It could be, but Asset Link just uses the default API permissions that farmOS sets up so the next step is to try those curl commands I provided to see if the farmOS API is working.

**Comment by altix12** [comment]
> > Le richieste HTTP POST funzionano correttamente .... potrebbe essere qualche problema con i permessi di scrittura di asset link?
> 
> Potrebbe essere, ma Asset Link utilizza solo le autorizzazioni API predefinite impostate da farmOS, quindi il passaggio successivo è provare quei comandi curl che ho fornito per vedere se l'API farmOS funziona.

farmos api seem to be working properly.... and as if asset link doesn't connect to server to create new data but only able to read

**Comment by symbioquine** [comment]
What are the request headers for the failing HTTP POST request to `/api/log/observation`?

**Comment by altix12** [comment]
> > What are the response headers?
> 
> ![Screenshot 2023-03-06 alle 19 42 58](https://user-images.githubusercontent.com/33596048/223202271-3cb37b0d-6055-4934-a8f6-058efc24305b.png)

This is the request header for the  failed HTTP POST

**Comment by symbioquine** [comment]
> This is the request header for the failed HTTP POST

That screenshot only shows the first one, but there are almost certainly more request headers if you scrolled down.

**Comment by altix12** [comment]
> > This is the request header for the failed HTTP POST
> 
> That screenshot only shows the first one, but there are almost certainly more request headers if you scrolled down.
![Screenshot 2023-03-07 alle 07 54 24](https://user-images.githubusercontent.com/33596048/223347227-d7e6a8be-e498-430c-9b43-695f08a11d7e.png)
![Screenshot 2023-03-07 alle 07 55 01](https://user-images.githubusercontent.com/33596048/223347239-279643a5-1296-4658-b606-3773a3be3bb2.png)

**Comment by altix12** [comment]
@symbioquine this is the error console... maybe there are requests /subrequests for writing data as well as reading data from the server?
![Screenshot 2023-03-07 alle 07 59 25](https://user-images.githubusercontent.com/33596048/223348478-4b0a86f1-59bf-4ba1-8ab3-690862adaeb2.png)

**Comment by altix12** [comment]
@symbioquine any news for this bug that prevents the creation of tasks via asset links?

**Comment by symbioquine** [comment]
> any news for this bug that prevents the creation of tasks via asset links?

Maybe if you can right click on the failing `/api/log/observation` request and do "Copy -> Copy as cURL", then try running that in the terminal and provide a screenshot of the command + output?

It might also be worth running the following again and providing a screenshot of the command + output;

> ```shell
> OAUTH2_ACCESS_TOKEN=`curl -X POST -d "grant_type=password&username=root&password=test&client_id=farm&scope=farm_manager" https://mysite.example.com/oauth/token | grep -Po 'access_token":"\K[^"]+'`
> curl -X POST --header "Authorization: Bearer $OAUTH2_ACCESS_TOKEN" --header 'Content-type: application/vnd.api+json' -d '{ "data": { "type": "log--observation", "attributes": { "name": "Testing Observation 123" } } }' "https://mysite.example.com/api/log/observation"
> ```
>
> Note: Obviously, you'll have to customize the urls and username/password in the commands above

**Comment by altix12** [comment]
![Screenshot 2023-03-08 alle 19 03 27](https://user-images.githubusercontent.com/33596048/223793996-0ecdbb3b-5f0d-4d07-976f-c179b3434913.png)

**Comment by altix12** [comment]
@symbioquine  curl write error ?  its a problem with expire token ?

**Comment by symbioquine** [comment]
> curl write error ? its a problem with expire token ?

@altix12 Nope, just that your grep doesn't support the `-P` flag.

I'm guessing you're probably on a Mac which comes with a very limited version of the `grep` command. You need to use GNU grep for my instructions above to work. See https://apple.stackexchange.com/questions/193288/how-to-install-and-use-gnu-grep-in-macos

**Comment by altix12** [comment]
![screenshot](https://user-images.githubusercontent.com/33596048/224251074-1504ecc0-7fef-462c-af8a-4505197ddc24.png)


@symbioquine here i tried on a linux machine where grep works but always get that write error

**Comment by symbioquine** [comment]
@altix12 

> here i tried on a linux machine where grep works but always get that write error

In general, permission errors are annoying that way because many things need to go right for access to be granted to a system and the error messages are intentionally vague since that itself can improve security.

My guess is that we're running into multiple problems; some with your farmOS configuration and some with the details of executing the troubleshooting steps themselves.

Regarding your screenshot, I don't think "Sticchi00" is a valid grant type, nor is "spitaleroo" the right key for the username. Hopefully those are both things you changed after the fact for the purposes of sharing the screenshot - and... if not, it might be advisable to change your password.

It's possible that the first command is failing somehow and the `$OAUTH2_ACCESS_TOKEN` variable isn't getting populated correctly.

To check that, we can add the `--silent --show-error --fail` flags to the first `curl` command to make sure it fails more clearly;

```shell
OAUTH2_ACCESS_TOKEN=`curl --silent --show-error --fail -X POST -d "grant_type=password&username=root&password=test&client_id=farm&scope=farm_manager" https://mysite.example.com/oauth/token | grep -Po 'access_token":"\K[^"]+'` && echo "success setting OAUTH2_ACCESS_TOKEN" || echo "failed setting OAUTH2_ACCESS_TOKEN"
```

In order to be worth proceeding, you need to get it to print "success setting OAUTH2_ACCESS_TOKEN" by modifying the first (`curl`) part of the command with your url/credentials.

**Comment by altix12** [comment]
@symbioquine  this is the result... the oauth2 is not setting? I don't know how to configure it because I didn't touch anything on its configuration when installing a new farmos installation


![Screenshot 2023-03-10 alle 08 28 28](https://user-images.githubusercontent.com/33596048/224251258-10649e29-6c6a-4669-8f2a-47efd912de94.png)

**Comment by symbioquine** [comment]
You should look for errors again on the Drupal side at `https://mysite.example.com/admin/reports/dblog`.

**Comment by altix12** [comment]
@symbioquine, I realized that the firewall was blocking some connections for me now I'm looking for if among these connections there are any related to asset links ... later I'll let you know if my firewall is the problem

**Comment by altix12** [comment]
@symbioquine the firewall was blocking some connections on asset links... now by rewriting the rules it seems to work even if I encountered a bug regarding the tasks that are created (the reference asset cannot be assigned to each task/log)

**Comment by altix12** [comment]
@symbioquineI'm trying asset link but I wanted to ask you if you could insert the assets inside the log/task creation page... 
a small example:

![Screenshot 2023-03-11 alle 13 47 44](https://user-images.githubusercontent.com/33596048/224485453-ea97d13b-c2ee-49b6-9837-877cfd87fd43.png)

**Comment by symbioquine** [comment]
Closing this since the original problem wasn't with Asset Link.
