### ISSUE TITLE
Compability with farmos 3.0 and Drupal 10

### ISSUE THREAD

**Issue by jorblad** [symbioquine/farmOS_asset_link#46]
As the release of farmos 3.0 draws closer it would be nice to be able to use asset link together with version 3.0 of farmos.
It might not need to much work but composer atleast need to be updated to allow drupal 10 to be used.

**Comment by symbioquine** [comment]
Asset Link has now been updated to be compatible with farmOS 3.x: https://www.drupal.org/project/farmos_asset_link/releases/1.0.0-alpha10
